services:
  - type: web
    name: nexopos
    env: php
    region: singapore
    buildCommand: "composer install && php artisan migrate --force && php artisan db:seed"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    plan: free
